# Get Posts
GET http://localhost:4000/post
###
# Create Post
POST http://localhost:4000/post
Content-Type: application/json

{ "title": "first post", "sender": "shai", "content": "my life is a lie" }
###
# Get Post by ID
GET http://localhost:4000/post/695a9c6ef52498fa30454939
###
# Update Post
PUT http://localhost:4000/post/695a9c6ef52498fa30454937
Content-Type: application/json 

{ "title": "first post2", "sender": "chang", "content": "my life is a lie 2" }
###
# Get Posts by Sender
GET http://localhost:4000/post?sender=chang
###
# Get Comments
GET http://localhost:4000/comment
###
# Get Comment
GET http://localhost:4000/comment/695a9e98c7b19ffc8e6d78ae
###
# Create Comment
POST http://localhost:4000/comment
Content-Type: application/json

{ "postId": "695a9c6ef52498fa30454937", "sender": "shai", "content": "testing" }
###
# Update Comment
PATCH http://localhost:4000/comment/695a9e98c7b19ffc8e6d78ae
Content-Type: application/json

{"content": "your life is a lie 3" }
###
# Delete Comment
DELETE http://localhost:4000/comment/695a9e98c7b19ffc8e6d78ae
###
# Get Comments by Post ID
GET http://localhost:4000/comment?postId=695a9c6ef52498fa30454937
###